#!/usr/bin/env python3
"""Build tool to package the HTML frontend into an embedded Python module.

Reads every asset from HTML/ and writes app/embedded_assets.py containing
pre-gzipped data, raw byte payloads, mime types, and ETags.
"""

from __future__ import annotations

import base64
import gzip
import hashlib
import mimetypes
import os
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
HTML_DIR = ROOT_DIR / "HTML"
OUT_FILE = ROOT_DIR / "app" / "embedded_assets.py"

mimetypes.init()
mimetypes.add_type("font/woff2", ".woff2")
mimetypes.add_type("font/ttf", ".ttf")
mimetypes.add_type("application/manifest+json", ".json")
mimetypes.add_type("application/vnd.android.package-archive", ".apk")


def bundle():
    if not HTML_DIR.is_dir():
        print(f"Error: HTML directory not found at {HTML_DIR}", file=sys.stderr)
        sys.exit(1)

    assets = {}
    total_raw = 0
    total_gz = 0

    for fname in sorted(os.listdir(HTML_DIR)):
        file_path = HTML_DIR / fname
        if not file_path.is_file():
            continue

        raw_bytes = file_path.read_bytes()
        total_raw += len(raw_bytes)

        gz_bytes = gzip.compress(raw_bytes, 9)
        total_gz += len(gz_bytes)

        mime, _ = mimetypes.guess_type(fname)
        if not mime:
            if fname.endswith(".apk"):
                mime = "application/vnd.android.package-archive"
            elif fname.endswith(".woff2"):
                mime = "font/woff2"
            elif fname.endswith(".ttf"):
                mime = "font/ttf"
            else:
                mime = "application/octet-stream"

        etag = f'"{hashlib.sha256(raw_bytes).hexdigest()[:16]}"'

        assets[fname] = {
            "mime": mime,
            "raw_size": len(raw_bytes),
            "gz_size": len(gz_bytes),
            "etag": etag,
            "gz_b64": base64.b64encode(gz_bytes).decode("ascii"),
        }

    lines = [
        '"""Auto-generated embedded frontend web assets for Iris.',
        "",
        "DO NOT EDIT DIRECTLY.",
        "Generated by tools/bundle_assets.py.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import base64",
        "import gzip",
        "from typing import Dict, Optional, Tuple",
        "",
        "# Map of filename -> {mime, raw_size, gz_size, etag, gz_b64}",
        "_ASSET_MANIFEST: Dict[str, dict] = {",
    ]

    for fname, meta in assets.items():
        lines.append(f"    {fname!r}: {{")
        lines.append(f"        'mime': {meta['mime']!r},")
        lines.append(f"        'raw_size': {meta['raw_size']},")
        lines.append(f"        'gz_size': {meta['gz_size']},")
        lines.append(f"        'etag': {meta['etag']!r},")
        lines.append(f"        'gz_b64': {meta['gz_b64']!r},")
        lines.append("    },")

    lines.extend([
        "}",
        "",
        "_CACHE_RAW: Dict[str, bytes] = {}",
        "_CACHE_GZ: Dict[str, bytes] = {}",
        "",
        "",
        "def has_asset(rel_path: str) -> bool:",
        "    return rel_path.lstrip('/') in _ASSET_MANIFEST",
        "",
        "",
        "def get_manifest(rel_path: str) -> Optional[dict]:",
        "    return _ASSET_MANIFEST.get(rel_path.lstrip('/'))",
        "",
        "",
        "def get_asset_bytes(rel_path: str, prefer_gzip: bool = True) -> Optional[Tuple[bytes, str, str, bool]]:",
        '    """Retrieve an asset by relative name.',
        "",
        "    Returns (content_bytes, content_type, etag, is_gzipped).",
        '    """',
        "    key = rel_path.lstrip('/')",
        "    meta = _ASSET_MANIFEST.get(key)",
        "    if not meta:",
        "        return None",
        "",
        "    if prefer_gzip:",
        "        if key not in _CACHE_GZ:",
        "            _CACHE_GZ[key] = base64.b64decode(meta['gz_b64'])",
        "        return _CACHE_GZ[key], meta['mime'], meta['etag'], True",
        "",
        "    if key not in _CACHE_RAW:",
        "        if key in _CACHE_GZ:",
        "            _CACHE_RAW[key] = gzip.decompress(_CACHE_GZ[key])",
        "        else:",
        "            gz = base64.b64decode(meta['gz_b64'])",
        "            _CACHE_GZ[key] = gz",
        "            _CACHE_RAW[key] = gzip.decompress(gz)",
        "    return _CACHE_RAW[key], meta['mime'], meta['etag'], False",
        "",
    ])

    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"Embedded {len(assets)} assets into {OUT_FILE.relative_to(ROOT_DIR)}: "
        f"raw {total_raw / (1024 * 1024):.2f} MB -> compressed {total_gz / (1024 * 1024):.2f} MB"
    )


if __name__ == "__main__":
    bundle()
